<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Descriptive Measures | Introduction to Statistics</title>
  <meta name="description" content="Chapter 2 Descriptive Measures | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Descriptive Measures | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 2 Descriptive Measures | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Descriptive Measures | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Chapter 2 Descriptive Measures | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Cappiello" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-data.html"/>
<link rel="next" href="probability-concepts.html"/>
<script src="libs/header-attrs-2.20.1/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#welcome-to-statistics" id="toc-welcome-to-statistics">Welcome to Statistics!</a>
<ul>
<li><a href="index.html#course-learning-outcomes" id="toc-course-learning-outcomes">Course Learning Outcomes</a></li>
<li><a href="index.html#for-the-instructor" id="toc-for-the-instructor">For the Instructor</a></li>
<li><a href="index.html#for-the-student" id="toc-for-the-student">For the Student</a>
<ul>
<li><a href="index.html#r-programming" id="toc-r-programming">R Programming</a></li>
</ul></li>
</ul></li>
<li><a href="introduction-to-data.html#introduction-to-data" id="toc-introduction-to-data"><span class="toc-section-number">1</span> Introduction to Data</a>
<ul>
<li><a href="introduction-to-data.html#chapter-overview" id="toc-chapter-overview"><span class="toc-section-number">1.1</span> Chapter Overview</a></li>
<li><a href="introduction-to-data.html#statistics-terminology" id="toc-statistics-terminology"><span class="toc-section-number">1.2</span> Statistics Terminology</a>
<ul>
<li><a href="introduction-to-data.html#r-entering-data" id="toc-r-entering-data">R: Entering Data</a></li>
<li><a href="introduction-to-data.html#section-exercises" id="toc-section-exercises">Section Exercises</a></li>
</ul></li>
<li><a href="introduction-to-data.html#sampling-and-design" id="toc-sampling-and-design"><span class="toc-section-number">1.3</span> Sampling and Design</a>
<ul>
<li><a href="introduction-to-data.html#statistical-sampling" id="toc-statistical-sampling"><span class="toc-section-number">1.3.1</span> Statistical Sampling</a></li>
<li><a href="introduction-to-data.html#experimental-design" id="toc-experimental-design"><span class="toc-section-number">1.3.2</span> Experimental Design</a></li>
<li><a href="introduction-to-data.html#r-random-number-generation" id="toc-r-random-number-generation">R: Random Number Generation</a></li>
<li><a href="introduction-to-data.html#section-exercises-1" id="toc-section-exercises-1">Section Exercises</a></li>
</ul></li>
<li><a href="introduction-to-data.html#frequency-distributions" id="toc-frequency-distributions"><span class="toc-section-number">1.4</span> Frequency Distributions</a>
<ul>
<li><a href="introduction-to-data.html#qualitative-variables" id="toc-qualitative-variables"><span class="toc-section-number">1.4.1</span> Qualitative Variables</a></li>
<li><a href="introduction-to-data.html#quantitative-variables" id="toc-quantitative-variables"><span class="toc-section-number">1.4.2</span> Quantitative Variables</a></li>
<li><a href="introduction-to-data.html#r-histograms" id="toc-r-histograms">R: Histograms</a></li>
</ul></li>
</ul></li>
<li><a href="descriptive-measures.html#descriptive-measures" id="toc-descriptive-measures"><span class="toc-section-number">2</span> Descriptive Measures</a>
<ul>
<li><a href="descriptive-measures.html#chapter-overview-1" id="toc-chapter-overview-1"><span class="toc-section-number">2.1</span> Chapter Overview</a></li>
<li><a href="descriptive-measures.html#measures-of-central-tendency" id="toc-measures-of-central-tendency"><span class="toc-section-number">2.2</span> Measures of Central Tendency</a>
<ul>
<li><a href="descriptive-measures.html#r-finding-measures-of-center" id="toc-r-finding-measures-of-center">R: Finding Measures of Center</a></li>
</ul></li>
<li><a href="descriptive-measures.html#measures-of-variability" id="toc-measures-of-variability"><span class="toc-section-number">2.3</span> Measures of Variability</a>
<ul>
<li><a href="descriptive-measures.html#r-finding-measures-of-variability" id="toc-r-finding-measures-of-variability">R: Finding Measures of Variability</a></li>
</ul></li>
<li><a href="descriptive-measures.html#measures-of-position" id="toc-measures-of-position"><span class="toc-section-number">2.4</span> Measures of Position</a>
<ul>
<li><a href="descriptive-measures.html#box-plots" id="toc-box-plots"><span class="toc-section-number">2.4.1</span> Box Plots</a></li>
<li><a href="descriptive-measures.html#r-measures-of-position" id="toc-r-measures-of-position">R: Measures of Position</a></li>
<li><a href="descriptive-measures.html#r-box-plots" id="toc-r-box-plots">R: Box Plots</a></li>
</ul></li>
<li><a href="descriptive-measures.html#descriptive-measures-for-populations" id="toc-descriptive-measures-for-populations"><span class="toc-section-number">2.5</span> Descriptive Measures for Populations</a></li>
</ul></li>
<li><a href="probability-concepts.html#probability-concepts" id="toc-probability-concepts"><span class="toc-section-number">3</span> Probability Concepts</a>
<ul>
<li><a href="probability-concepts.html#chapter-overview-2" id="toc-chapter-overview-2"><span class="toc-section-number">3.1</span> Chapter Overview</a></li>
<li><a href="probability-concepts.html#experiments-sample-spaces-and-events" id="toc-experiments-sample-spaces-and-events"><span class="toc-section-number">3.2</span> Experiments, Sample Spaces, and Events</a></li>
<li><a href="probability-concepts.html#probability-distributions" id="toc-probability-distributions"><span class="toc-section-number">3.3</span> Probability Distributions</a>
<ul>
<li><a href="probability-concepts.html#venn-diagrams" id="toc-venn-diagrams"><span class="toc-section-number">3.3.1</span> Venn Diagrams</a></li>
<li><a href="probability-concepts.html#probability-axioms" id="toc-probability-axioms"><span class="toc-section-number">3.3.2</span> Probability Axioms</a></li>
<li><a href="probability-concepts.html#exercises" id="toc-exercises">Exercises</a></li>
</ul></li>
<li><a href="probability-concepts.html#rules-of-probability" id="toc-rules-of-probability"><span class="toc-section-number">3.4</span> Rules of Probability</a>
<ul>
<li><a href="probability-concepts.html#addition-rules" id="toc-addition-rules"><span class="toc-section-number">3.4.1</span> Addition Rules</a></li>
<li><a href="probability-concepts.html#complements" id="toc-complements"><span class="toc-section-number">3.4.2</span> Complements</a></li>
</ul></li>
<li><a href="probability-concepts.html#conditional-probability" id="toc-conditional-probability"><span class="toc-section-number">3.5</span> Conditional Probability</a>
<ul>
<li><a href="probability-concepts.html#multiplication-rules" id="toc-multiplication-rules"><span class="toc-section-number">3.5.1</span> Multiplication Rules</a></li>
</ul></li>
</ul></li>
<li><a href="random-variables.html#random-variables" id="toc-random-variables"><span class="toc-section-number">4</span> Random Variables</a>
<ul>
<li><a href="random-variables.html#chapter-overview-3" id="toc-chapter-overview-3"><span class="toc-section-number">4.1</span> Chapter Overview</a></li>
<li><a href="random-variables.html#discrete-random-variables" id="toc-discrete-random-variables"><span class="toc-section-number">4.2</span> Discrete Random Variables</a>
<ul>
<li><a href="random-variables.html#the-mean-and-standard-deviation" id="toc-the-mean-and-standard-deviation"><span class="toc-section-number">4.2.1</span> The Mean and Standard Deviation</a></li>
</ul></li>
<li><a href="random-variables.html#the-binomial-distribution" id="toc-the-binomial-distribution"><span class="toc-section-number">4.3</span> The Binomial Distribution</a>
<ul>
<li><a href="random-variables.html#mean-and-variance" id="toc-mean-and-variance"><span class="toc-section-number">4.3.1</span> Mean and Variance</a></li>
<li><a href="random-variables.html#binomial-probabilities-in-r" id="toc-binomial-probabilities-in-r">Binomial Probabilities in R</a></li>
</ul></li>
<li><a href="random-variables.html#the-normal-distribution" id="toc-the-normal-distribution"><span class="toc-section-number">4.4</span> The Normal Distribution</a>
<ul>
<li><a href="random-variables.html#the-standard-normal-distribution" id="toc-the-standard-normal-distribution"><span class="toc-section-number">4.4.1</span> The Standard Normal Distribution</a></li>
</ul></li>
<li><a href="random-variables.html#area-under-the-standard-normal-curve" id="toc-area-under-the-standard-normal-curve"><span class="toc-section-number">4.5</span> Area Under the Standard Normal Curve</a>
<ul>
<li><a href="random-variables.html#r-normal-distribution-probabilities" id="toc-r-normal-distribution-probabilities">R: Normal Distribution Probabilities</a></li>
</ul></li>
<li><a href="random-variables.html#working-with-normally-distributed-variables" id="toc-working-with-normally-distributed-variables"><span class="toc-section-number">4.6</span> Working with Normally Distributed Variables</a>
<ul>
<li><a href="random-variables.html#normal-distribution-probabilities" id="toc-normal-distribution-probabilities"><span class="toc-section-number">4.6.1</span> Normal Distribution Probabilities</a></li>
<li><a href="random-variables.html#empirical-rule-for-variables" id="toc-empirical-rule-for-variables"><span class="toc-section-number">4.6.2</span> Empirical Rule for Variables</a></li>
<li><a href="random-variables.html#percentiles" id="toc-percentiles"><span class="toc-section-number">4.6.3</span> Percentiles</a></li>
</ul></li>
</ul></li>
<li><a href="introduction-to-confidence-intervals.html#introduction-to-confidence-intervals" id="toc-introduction-to-confidence-intervals"><span class="toc-section-number">5</span> Introduction to Confidence Intervals</a>
<ul>
<li><a href="introduction-to-confidence-intervals.html#chapter-overview-4" id="toc-chapter-overview-4"><span class="toc-section-number">5.1</span> Chapter Overview</a></li>
<li><a href="introduction-to-confidence-intervals.html#sampling-distributions" id="toc-sampling-distributions"><span class="toc-section-number">5.2</span> Sampling Distributions</a>
<ul>
<li><a href="introduction-to-confidence-intervals.html#sampling-error" id="toc-sampling-error"><span class="toc-section-number">5.2.1</span> Sampling Error</a></li>
<li><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem" id="toc-the-central-limit-theorem"><span class="toc-section-number">5.2.2</span> The Central Limit Theorem</a></li>
</ul></li>
<li><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals" id="toc-developing-confidence-intervals"><span class="toc-section-number">5.3</span> Developing Confidence Intervals</a>
<ul>
<li><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval" id="toc-interpreting-a-confidence-interval"><span class="toc-section-number">5.3.1</span> Interpreting a Confidence Interval</a></li>
<li><a href="introduction-to-confidence-intervals.html#exercises-1" id="toc-exercises-1"><span class="toc-section-number">5.3.2</span> Exercises</a></li>
</ul></li>
<li><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence" id="toc-other-levels-of-confidence"><span class="toc-section-number">5.4</span> Other Levels of Confidence</a>
<ul>
<li><a href="introduction-to-confidence-intervals.html#r-finding-critical-values" id="toc-r-finding-critical-values">R: Finding Critical Values</a></li>
<li><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval" id="toc-breaking-down-a-confidence-interval"><span class="toc-section-number">5.4.1</span> Breaking Down a Confidence Interval</a></li>
<li><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size" id="toc-confidence-level-precision-and-sample-size"><span class="toc-section-number">5.4.2</span> Confidence Level, Precision, and Sample Size</a></li>
<li><a href="introduction-to-confidence-intervals.html#exercises-2" id="toc-exercises-2"><span class="toc-section-number">5.4.3</span> Exercises</a></li>
</ul></li>
<li><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean" id="toc-confidence-intervals-for-a-mean"><span class="toc-section-number">5.5</span> Confidence Intervals for a Mean</a>
<ul>
<li><a href="introduction-to-confidence-intervals.html#the-t-distribution" id="toc-the-t-distribution"><span class="toc-section-number">5.5.1</span> The T-Distribution</a></li>
<li><a href="introduction-to-confidence-intervals.html#r-t-critical-values" id="toc-r-t-critical-values">R: T Critical Values</a></li>
</ul></li>
<li><a href="introduction-to-confidence-intervals.html#r-confidence-intevals-for-a-mean" id="toc-r-confidence-intevals-for-a-mean">R: Confidence Intevals for a Mean</a></li>
</ul></li>
<li><a href="introduction-to-hypothesis-testing.html#introduction-to-hypothesis-testing" id="toc-introduction-to-hypothesis-testing"><span class="toc-section-number">6</span> Introduction to Hypothesis Testing</a>
<ul>
<li><a href="introduction-to-hypothesis-testing.html#chapter-overview-5" id="toc-chapter-overview-5"><span class="toc-section-number">6.1</span> Chapter Overview</a></li>
<li><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing" id="toc-logic-of-hypothesis-testing"><span class="toc-section-number">6.2</span> Logic of Hypothesis Testing</a>
<ul>
<li><a href="introduction-to-hypothesis-testing.html#decision-errors" id="toc-decision-errors"><span class="toc-section-number">6.2.1</span> Decision Errors</a></li>
</ul></li>
<li><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing" id="toc-confidence-interval-approach-to-hypothesis-testing"><span class="toc-section-number">6.3</span> Confidence Interval Approach to Hypothesis Testing</a></li>
<li><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing" id="toc-critical-value-approach-to-hypothesis-testing"><span class="toc-section-number">6.4</span> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li><a href="introduction-to-hypothesis-testing.html#test-statistics" id="toc-test-statistics"><span class="toc-section-number">6.4.1</span> Test statistics</a></li>
</ul></li>
<li><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing" id="toc-p-value-approach-to-hypothesis-testing"><span class="toc-section-number">6.5</span> P-Value Approach to Hypothesis Testing</a>
<ul>
<li><a href="introduction-to-hypothesis-testing.html#p-values" id="toc-p-values"><span class="toc-section-number">6.5.1</span> P-Values</a></li>
</ul></li>
<li><a href="introduction-to-hypothesis-testing.html#r-hypothesis-tests-for-a-mean" id="toc-r-hypothesis-tests-for-a-mean">R: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li><a href="inference-for-a-proportion.html#inference-for-a-proportion" id="toc-inference-for-a-proportion"><span class="toc-section-number">7</span> Inference for a Proportion</a>
<ul>
<li><a href="inference-for-a-proportion.html#chapter-overview-6" id="toc-chapter-overview-6"><span class="toc-section-number">7.1</span> Chapter Overview</a></li>
<li><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion" id="toc-confidence-intervals-for-a-proportion"><span class="toc-section-number">7.2</span> Confidence Intervals for a Proportion</a></li>
<li><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion" id="toc-hypothesis-tests-for-a-proportion"><span class="toc-section-number">7.3</span> Hypothesis Tests for a Proportion</a>
<ul>
<li><a href="inference-for-a-proportion.html#confidence-interval-approach" id="toc-confidence-interval-approach"><span class="toc-section-number">7.3.1</span> Confidence Interval Approach</a></li>
<li><a href="inference-for-a-proportion.html#critical-value-approach" id="toc-critical-value-approach"><span class="toc-section-number">7.3.2</span> Critical Value Approach</a></li>
<li><a href="inference-for-a-proportion.html#p-value-approach" id="toc-p-value-approach"><span class="toc-section-number">7.3.3</span> P-Value Approach</a></li>
</ul></li>
<li><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion" id="toc-r-hypothesis-tests-for-a-proportion">R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li><a href="inference-comparing-parameters.html#inference-comparing-parameters" id="toc-inference-comparing-parameters"><span class="toc-section-number">8</span> Inference: Comparing Parameters</a>
<ul>
<li><a href="inference-comparing-parameters.html#chapter-overview-7" id="toc-chapter-overview-7"><span class="toc-section-number">8.1</span> Chapter Overview</a></li>
<li><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions" id="toc-hypothesis-tests-for-two-proportions"><span class="toc-section-number">8.2</span> Hypothesis Tests for Two Proportions</a>
<ul>
<li><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions" id="toc-confidence-intervals-for-two-proportions"><span class="toc-section-number">8.2.1</span> Confidence Intervals for Two Proportions</a></li>
<li><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values" id="toc-critical-values-test-statistics-and-p-values"><span class="toc-section-number">8.2.2</span> Critical Values, Test Statistics, and P-Values</a></li>
<li><a href="inference-comparing-parameters.html#r-hypothesis-tests-for-two-proportions" id="toc-r-hypothesis-tests-for-two-proportions">R: Hypothesis Tests for Two Proportions</a></li>
</ul></li>
<li><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means" id="toc-hypothesis-tests-for-two-means"><span class="toc-section-number">8.3</span> Hypothesis Tests for Two Means</a>
<ul>
<li><a href="inference-comparing-parameters.html#paired-samples" id="toc-paired-samples"><span class="toc-section-number">8.3.1</span> Paired Samples</a></li>
<li><a href="inference-comparing-parameters.html#independent-samples" id="toc-independent-samples"><span class="toc-section-number">8.3.2</span> Independent Samples</a></li>
<li><a href="inference-comparing-parameters.html#r-hypothesis-tests-for-two-means" id="toc-r-hypothesis-tests-for-two-means">R: Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li><a href="chi-square-tests.html#chi-square-tests" id="toc-chi-square-tests"><span class="toc-section-number">9</span> Chi-Square Tests</a>
<ul>
<li><a href="chi-square-tests.html#chapter-overview-8" id="toc-chapter-overview-8"><span class="toc-section-number">9.1</span> Chapter Overview</a></li>
<li><a href="chi-square-tests.html#inference-for-a-population-variance" id="toc-inference-for-a-population-variance"><span class="toc-section-number">9.2</span> Inference for a Population Variance</a>
<ul>
<li><a href="chi-square-tests.html#the-chi-square-distribution" id="toc-the-chi-square-distribution"><span class="toc-section-number">9.2.1</span> The Chi-Square Distribution</a></li>
</ul></li>
<li><a href="chi-square-tests.html#the-ratio-of-two-variances" id="toc-the-ratio-of-two-variances"><span class="toc-section-number">9.3</span> The Ratio of Two Variances</a></li>
<li><a href="chi-square-tests.html#goodness-of-fit" id="toc-goodness-of-fit"><span class="toc-section-number">9.4</span> Goodness of Fit</a></li>
<li><a href="chi-square-tests.html#contingency-tables" id="toc-contingency-tables"><span class="toc-section-number">9.5</span> Contingency Tables</a></li>
</ul></li>
<li><a href="anova.html#anova" id="toc-anova"><span class="toc-section-number">10</span> ANOVA</a>
<ul>
<li><a href="anova.html#chapter-overview-9" id="toc-chapter-overview-9"><span class="toc-section-number">10.1</span> Chapter Overview</a></li>
<li><a href="anova.html#what-is-the-analysis-of-variance-anova" id="toc-what-is-the-analysis-of-variance-anova"><span class="toc-section-number">10.2</span> What is the Analysis of Variance (ANOVA)</a></li>
<li><a href="anova.html#the-f-distribution" id="toc-the-f-distribution"><span class="toc-section-number">10.3</span> The F-Distribution</a></li>
<li><a href="anova.html#multiple-comparisons-and-type-i-error-rate" id="toc-multiple-comparisons-and-type-i-error-rate"><span class="toc-section-number">10.4</span> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li><a href="regression-and-correlation.html#regression-and-correlation" id="toc-regression-and-correlation"><span class="toc-section-number">11</span> Regression and Correlation</a>
<ul>
<li><a href="regression-and-correlation.html#chapter-overview-10" id="toc-chapter-overview-10"><span class="toc-section-number">11.1</span> Chapter Overview</a></li>
<li><a href="regression-and-correlation.html#linear-equations" id="toc-linear-equations"><span class="toc-section-number">11.2</span> Linear Equations</a></li>
<li><a href="regression-and-correlation.html#correlation" id="toc-correlation"><span class="toc-section-number">11.3</span> Correlation</a></li>
<li><a href="regression-and-correlation.html#finding-a-regression-line" id="toc-finding-a-regression-line"><span class="toc-section-number">11.4</span> Finding a Regression Line</a>
<ul>
<li><a href="regression-and-correlation.html#coefficient-of-determination" id="toc-coefficient-of-determination"><span class="toc-section-number">11.4.1</span> Coefficient of Determination</a></li>
</ul></li>
</ul></li>
<li><a href="appendices.html#appendices" id="toc-appendices">Appendices</a>
<ul>
<li><a href="appendices.html#appendix-a-important-links-and-additional-resources" id="toc-appendix-a-important-links-and-additional-resources">Appendix A: Important Links and Additional Resources</a>
<ul>
<li><a href="appendices.html#applets" id="toc-applets">Applets</a></li>
<li><a href="appendices.html#run-r-online" id="toc-run-r-online">Run R Online</a></li>
</ul></li>
<li><a href="appendices.html#appendix-b-average-deviance" id="toc-appendix-b-average-deviance">Appendix B: Average Deviance</a></li>
<li><a href="appendices.html#appendix-c-deriving-a-confidence-interval" id="toc-appendix-c-deriving-a-confidence-interval">Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-measures" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Descriptive Measures<a href="descriptive-measures.html#descriptive-measures" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="chapter-overview-1" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Chapter Overview<a href="descriptive-measures.html#chapter-overview-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous chapter, we thought about descriptive statistics using tables and graphs. Next, we summarize data by computing numbers. Some of these numbers you may already be familiar with, such as averages and percentiles. Numbers used to describe data are called <em>descriptive measures</em>.</p>
<p><strong>Chapter Learning Objectives/Outcomes</strong></p>
<p>After completing Chapter 2, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Calculate and interpret measures of center.</li>
<li>Calculate and interpret measures of variation.</li>
<li>Find and interpret measures of position.</li>
<li>Summarize data using boxplots.</li>
</ol>
<p><strong>R objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Generate measures of center.</li>
<li>Generate measures of variability.</li>
<li>Generate measures of position.</li>
<li>Create box plots.</li>
</ol>
<p>This chapter’s outcomes correspond to course outcomes (1) organize, summarize, and interpret data in tabular, graphical, and pictorial formats, (2) organize and interpret bivariate data and learn simple linear regression and correlation, and (6) apply statistical inference techniques of parameter estimation such as point estimation and confidence interval estimation.</p>
</div>
<div id="measures-of-central-tendency" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Measures of Central Tendency<a href="descriptive-measures.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One research question we might ask is : what values are most common or most likely?</p>
<p><strong>Mode</strong>: the most commonly occurring value. We can use this for numeric variables, but typically we use the mode when talking about categorical data.</p>
<p><strong>Mean</strong>: this is what we usually think of as the “average”. Denoted <span class="math inline">\(\bar{x}\)</span>. Add up all of the values and divide by the number of observations (<span class="math inline">\(n\)</span>):
<span class="math display">\[
  \bar{x} = \frac{x_1 + x_2 + \dots + x_n}{n} = \sum_{i=1}^n \frac{x_i}{n}
\]</span>
where <span class="math inline">\(x_i\)</span> denotes the <span class="math inline">\(i\)</span>th observation and <span class="math inline">\(\sum_{i=1}^n\)</span> is the sum of all observations from 1 through <span class="math inline">\(n\)</span>. This is called <em>summation notation</em>.</p>
<p><strong>Median</strong>: the middle number when the data are ordered from smallest to largest.</p>
<ul>
<li>If there are an odd number of observations, this will be the number in the middle:
<center>
{1, 3, <strong>7</strong>, 9, 9} has median 7
</center></li>
<li>If there are an even number of observations, there will be two numbers in the middle. The median will be their average.
<center>
{1, 2, <strong>4, 7</strong>, 9, 9} has median <span class="math inline">\(\frac{4+7}{2}=5.5\)</span>
</center></li>
</ul>
<p>The mean is sensitive to extreme values and skew. The median is not!</p>
<table border="1">
<tbody>
<tr>
<td style="width: 9%; text-align: center;">
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(x\)</span>: 1, 3, 7, 9, 9
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(y\)</span>: 1, 3, 7, 9, 45
</td>
</tr>
<tr>
<td style="width: 9%; text-align: center;">
<strong>Median</strong>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\text{median} = 7\)</span>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\text{median} = 7\)</span>
</td>
</tr>
<tr>
<td style="width: 9%; text-align: center;">
<strong>Mean</strong>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\bar{x} = \frac{29}{5} = 5.8\)</span>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\bar{y} = \frac{65}{5} = 13\)</span>
</td>
</tr>
</tbody>
</table>
<p>Notice how changing that 9 out for a 45 changes the <em>mean</em> a lot! But the <em>median</em> is 7 for both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p>Because the median is not affected by extreme observations or skew, we say it is a <strong>resistant measure</strong> or that it is <strong>robust</strong>.</p>
<p>Which measure should we use?</p>
<ul>
<li>Mean: symmetric, numeric data</li>
<li>Median: skewed, numeric data</li>
<li>Mode: categorical data</li>
</ul>
<p>Note: If the mean and median are roughly equal, it is reasonable to assume the distribution is roughly symmetric.</p>
<div id="r-finding-measures-of-center" class="section level3 unnumbered hasAnchor">
<h3>R: Finding Measures of Center<a href="descriptive-measures.html#r-finding-measures-of-center" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a mean in R, we use the command <code>mean</code>. Let’s use the <code>Loblolly</code> pine data again and find the <code>mean</code> tree height.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="descriptive-measures.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span>
<span id="cb13-2"><a href="descriptive-measures.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(height)</span></code></pre></div>
<pre><code>## [1] 32.3644</code></pre>
<p>From R, we can see that the sample mean height of the Loblolly pines is 32.36 feet. (Note that R will often print things out with ## and a number in square brackets. This is just to help us keep track of things if we write a lot of lines of code. You can ignore that number in the brackets!)</p>
<p>Is a mean the appropriate measure of center? We can quickly check the skew with a histogram:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="descriptive-measures.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(height)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>It might be a little bit hard to tell with this histogram, but it does not look particularly skewed. Let’s use our other trick: if the mean and median are approximatly equal, we can say the distribution is approximately symmetric (and therefore the mean is an appropriate measure of center). To calculate the median, we use the command <code>median</code>:</p>
<pre><code>## [1] 34</code></pre>
<p>The sample median of the Loblolly pine heights is 34 feet. Since the mean and median are approximately equal, it would be reasonable to use the mean in this case. To find a mode (for a categorical variable), we would repeat the same process but with the command <code>mode</code>.</p>
</div>
</div>
<div id="measures-of-variability" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Measures of Variability<a href="descriptive-measures.html#measures-of-variability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How much do the data vary?</p>
<p>Should we care? Yes! The more variable the data, the harder it is to be confident in our measures of center!</p>
<p>If you live in a place with extremely variable weather, it is going to be much harder to be confident in how to dress for tomorrow’s weather… but if you live in a place where the weather is always the same, it’s much easier to be confident in what you plan to wear.</p>
<p>We want to think about how far observations are from the measure of center.</p>
<p>One easy way to think about variability is the <strong>range</strong> of the data: <span class="math display">\[\text{range} = \text{maximum} - \text{minimum}\]</span> This is quick and convenient, but it is <em>extremely</em> sensitive to outliers! It also takes into account only two of the observations - we would prefer a measure of variability that takes into account <em>all</em> the observations.</p>
<p><strong>Deviation</strong> is the distance of an observation from the mean: <span class="math inline">\(x - \bar{x}\)</span>. If we want to think about how far - on average - a typical observation is from the center, our intuition might be to take the average deviance… but it turns out that summing up the deviances will <em>always</em> result in 0! Conceptually, this is because the stuff below the mean (negative numbers) and the stuff above the mean (positive numbers) end up canceling each other out until we end up at 0. (If you are interested, <em>Appendix A: Average Deviance</em> has a mathematical proof of this using some relatively straightforward algebra.)</p>
<p>One way to deal with this is to make all of the numbers positive, which we accomplish by squaring the deviance.</p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Deviance</th>
<th align="center">Squared Deviance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(x\)</span></td>
<td align="center"><span class="math inline">\(x - \bar{x}\)</span></td>
<td align="center"><span class="math inline">\((x - \bar{x})^2\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">-1.2</td>
<td align="center">1.44</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">1.8</td>
<td align="center">3.24</td>
</tr>
<tr class="even">
<td align="center">3</td>
<td align="center">-0.2</td>
<td align="center">0.04</td>
</tr>
<tr class="odd">
<td align="center">4</td>
<td align="center">0.8</td>
<td align="center">0.64</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">-1.2</td>
<td align="center">1.44</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{x}=3.2\)</span></td>
<td align="center">Total = 0</td>
<td align="center">Total = 6.8</td>
</tr>
</tbody>
</table>
<p><strong>Variance</strong> (denoted <span class="math inline">\(s^2\)</span>) is the average squared distance from the mean:
<span class="math display">\[
  s^2 = \frac{(x_1-\bar{x})^2 + (x_2-\bar{x})^2 + \dots + (x_n-\bar{x})^2}{n-1} = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2
\]</span>
where <span class="math inline">\(n\)</span> is the sample size. Notice that we divide by <span class="math inline">\(n-1\)</span> and NOT by <span class="math inline">\(n\)</span>. There are some mathematical reasons why we do this, but the short version is that it’ll be a better estimate when we talk about inference.</p>
<p>Finally, we come to <strong>standard deviation</strong> (denoted <span class="math inline">\(s\)</span>). <span class="math display">\[s = \sqrt{s^2}\]</span> The standard deviation is the square root of the variance. We say that a “typical” observation is within about one standard deviation of the mean (between <span class="math inline">\(\bar{x}-s\)</span> and <span class="math inline">\(\bar{x}+s\)</span>).</p>
<p>In practice (including in this class), we will use a computer to calculate the variance and standard deviation.</p>
<p>We will think about one more measure of variability, the interquartile range, in the next section.</p>
<div id="r-finding-measures-of-variability" class="section level3 unnumbered hasAnchor">
<h3>R: Finding Measures of Variability<a href="descriptive-measures.html#r-finding-measures-of-variability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a range in R, we get started using the command <code>range</code>. Let’s keep using the <code>Loblolly</code> pine data again and find the <code>mean</code> tree height.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="descriptive-measures.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="descriptive-measures.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(height)</span></code></pre></div>
<pre><code>## [1]  3.46 64.10</code></pre>
<p>This command gives us the minimum and maximum values. Then to calculate the range, we would find <span class="math inline">\(64.10 - 3.46\)</span>. We can also do this in R, because R doubles as a calculator!</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="descriptive-measures.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fl">64.1</span> <span class="sc">-</span> <span class="fl">3.46</span></span></code></pre></div>
<pre><code>## [1] 60.64</code></pre>
<p>The sample range of the Loblolly pine heights is 60.64 feet.</p>
<p>To find the variance and standard deviation, we use the commands <code>var</code> and <code>sd</code>, respectively:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="descriptive-measures.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(height)</span></code></pre></div>
<pre><code>## [1] 427.3979</code></pre>
<p>The sample variance of the Loblolly pine heights is 427.4.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="descriptive-measures.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(height)</span></code></pre></div>
<pre><code>## [1] 20.6736</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="descriptive-measures.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>
<p>The sample standard deviation of the Loblolly pine heights is 20.67 feet.</p>
</div>
</div>
<div id="measures-of-position" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Measures of Position<a href="descriptive-measures.html#measures-of-position" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <strong>interquartile range</strong> (<strong>IQR</strong>) represents the middle 50% of the data.</p>
<p>Recall that the <em>median</em> cut the data in half: 50% of the data is below and 50% is above the median. This is also called the <strong>50th percentile</strong>. The <strong><span class="math inline">\(p\)</span>th percentile</strong> is the value for which <span class="math inline">\(p\)</span>% of the data is below it.</p>
<p>To get the middle 50%, we will split the data into four parts:</p>
<table>
<thead>
<tr class="header">
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">25%</td>
<td align="center">25%</td>
<td align="center">25%</td>
<td align="center">25%</td>
</tr>
</tbody>
</table>
<p>The 25th and 75th percentiles, along with the median, divide the data into four parts. We call these three measurements the <strong>quartiles</strong>:</p>
<ul>
<li><strong>Q1</strong>, the first quartile, is the median of the lower 50% of the data.</li>
<li><strong>Q2</strong>, the second quartile, is the median.</li>
<li><strong>Q3</strong>, the third quartile, is the median of the upper 50% of the data.</li>
</ul>
<blockquote>
<p><em>Example:</em> Consider {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}</p>
<ul>
<li>Cutting the data in half: {1, 2, 3, 4, 5 | 6, 7, 8, 9, 10}, the median (Q2) is <span class="math inline">\(\frac{5+6}{2}=5.5\)</span>.</li>
<li>Q1 is the median of {1, 2, 3, 4, 5}, or 3</li>
<li>Q3 is the median of {6, 7, 8, 9, 10}, or 8</li>
</ul>
</blockquote>
<p><strong>Note:</strong> this is a “quick and dirty” way of finding quartiles. A computer will give a more exact result.</p>
<p>Then the interquartile range is
<span class="math display">\[
  \text{IQR} = \text{Q3}-\text{Q1}
\]</span></p>
<p>This is another measure of variability and is resistant to extreme values. In general, we prefer the mean and standard deviation when the data are symmetric and we prefer the median and IQR when the data are skewed.</p>
<div id="box-plots" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Box Plots<a href="descriptive-measures.html#box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our measures of position are the foundation for constructing what we call a box plot, which summarizes the data with 5 statistics plus extreme observations:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Drawing a box plot:</p>
<ol style="list-style-type: decimal">
<li>Draw the vertical axis to include all possible values in the data.</li>
<li>Draw a horizontal line at the median, at <span class="math inline">\(\text{Q1}\)</span>, and at <span class="math inline">\(\text{Q3}\)</span>. Use these to form a box.</li>
<li>Draw the <strong>whiskers</strong>. The whiskers’ upper limit is <span class="math inline">\(\text{Q3}+1.5\times\text{IQR}\)</span> and the lower limit is <span class="math inline">\(\text{Q1}-1.5\times\text{IQR}\)</span>. The actual whiskers are then drawn <em>at the next closest data points within the limits</em>.</li>
<li>Any points outside the whisker limits are included as individual points. These are <strong>potential outliers</strong>.</li>
</ol>
<p>(Potential) outliers can help us…</p>
<ul>
<li>examine skew (outliers in the negative direction suggest left skew; outliers in the positive direction suggest right skew).</li>
<li>identify issues with data collection or entry, especially if the value of the outliers doesn’t make sense.</li>
</ul>
<p>As with most things in this text, we won’t draw a lot of boxplots by hand. However, understanding how they are drawn will help us understand how to interpret them!</p>
</div>
<div id="r-measures-of-position" class="section level3 unnumbered hasAnchor">
<h3>R: Measures of Position<a href="descriptive-measures.html#r-measures-of-position" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s continue using the Loblolly pine data.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="descriptive-measures.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span></code></pre></div>
<p>We can get the quartiles quickly using the <code>summary</code> command. This will also give us the minimum, mean, and maximum. That’s fine!</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="descriptive-measures.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(height)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    3.46   10.47   34.00   32.36   51.36   64.10</code></pre>
<p>So <span class="math inline">\(Q1 = 10.46\)</span>, <span class="math inline">\(Q2 = \text{Median} = 34\)</span>, and <span class="math inline">\(Q3 = 51.35\)</span>. We can also quickly get the interquartile range using the <code>IQR</code> command.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="descriptive-measures.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(height)</span></code></pre></div>
<pre><code>## [1] 40.895</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="descriptive-measures.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>
</div>
<div id="r-box-plots" class="section level3 unnumbered hasAnchor">
<h3>R: Box Plots<a href="descriptive-measures.html#r-box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="descriptive-measures.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span></code></pre></div>
<p>To create a boxplot in R, we use the command <code>boxplot</code>. We can use some of the same arguments we used with the <code>hist</code> command to give it titles and color:</p>
<ul>
<li><code>main</code> is where I can give the plot a new title. (Make sure to put the title in quotes!)</li>
<li><code>ylab</code> is the y-axis (vertical axis) title.</li>
<li><code>col</code> allows us to give R a specific color for the bars.</li>
</ul>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="descriptive-measures.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(height,</span>
<span id="cb34-2"><a href="descriptive-measures.html#cb34-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot of Loblolly Pine Heights&quot;</span>, </span>
<span id="cb34-3"><a href="descriptive-measures.html#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Height (feet)&quot;</span>,</span>
<span id="cb34-4"><a href="descriptive-measures.html#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>R will automatically create the entire box plot, including showing any outliers. (Which we should note that there aren’t any in the <code>height</code> variable!)</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="descriptive-measures.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>
</div>
</div>
<div id="descriptive-measures-for-populations" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Descriptive Measures for Populations<a href="descriptive-measures.html#descriptive-measures-for-populations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far, we’ve thought about calculating various descriptive statistics from a sample, but our long-term goal is to estimate descriptive information about a population. At the population level, these values are called <strong>parameters</strong>.</p>
<p>When we find a measure of center, spread, or position, we use a sample to calculate a single value. These single values are called <strong>point estimates</strong> and they are used to <em>estimate</em> the corresponding population parameter. For example, we use <span class="math inline">\(\bar{x}\)</span> to estimate the population mean, denoted <span class="math inline">\(\mu\)</span> (Greek letter “mu”) and <span class="math inline">\(s\)</span> to estimate the population standard deviation, denoted <span class="math inline">\(\sigma\)</span> (Greek letter “sigma”).</p>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Point Estimate</th>
<th>Parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>sample mean: <span class="math inline">\(\bar{x}\)</span></td>
<td>population mean: <span class="math inline">\(\mu\)</span></td>
</tr>
<tr class="even">
<td>sample standard deviation: <span class="math inline">\(s\)</span></td>
<td>population standard deviation: <span class="math inline">\(\sigma\)</span></td>
</tr>
</tbody>
</table>
<p>…and so on and so forth. For each quantity we calculate from a sample (point estimate), there is some corresponding unknown population level value (parameter) that we wish to estimate.</p>
<p>We will discuss this in more detail when we discuss Random Variables and Statistical Inference.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability-concepts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["IntroStats.pdf", "IntroStats.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
