theme: jekyll-theme-minimal
title: Lauren Cappiello
description: Applied Statistics PhD candidate working under the supervision of Dr. Zhiwei Zhang at the University of California, Riverside

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
