---
title: "3.2 Sample Spaces and Events"
author: "Dr. Lauren Parker"
output:
  ioslides_presentation: 
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Probability

**Probability** is the science of uncertainty. 

- When we run an experiment, we are unsure of what the outcome will be. 
- Because of this uncertainty, we say an experiment is a **random process**.

## Probability

The probability of an event is the proportion of times it would occur if the experiment were run infinitely many times. 

For a collection of *equally likely events*, this looks like:
\[
  \text{probability of event} = \frac{\text{number of ways event can occur}}{\text{number of possible outcomes}}
\]

An **event** is some specified possible outcome (or collection of outcomes) we are interested in observing. 

## Example

You want to roll a 6 on a six-sided die.

- There are six possible outcomes $\{1,2,3,4,5,6\}$. 
- We assume that each die face is equally likely to appear on a single roll of the die.
    - The die is *fair*.
- The probability of rolling a 6 is $$\frac{\text{number of ways to roll a 6}}{\text{number of possible rolls}} = \frac{1}{6}$$

## Example

We can extend this to a collection of events.

- The probability of rolling a 5 or a 6: $$\frac{\text{number of ways to roll a 5 or 6}}{\text{number of possible rolls}} = \frac{2}{6}$$

## Sample Spaces

The collection of all possible outcomes is called a **sample space**, denoted $S$. 

- For the six-sided die, $S=\{1,2,3,4,5,6\}$.

## Probability Notation

To simplify our writing, we use **probability notation**:

- Events are assigned capital letters.
- $P(A)$ denotes the probability of event $A$.
- Sometimes we will also shorten simple events to just a number. 
    - For example, $P(1)$ might represent "the probability of rolling a 1".

***

We can estimate probabilities from a sample using a frequency distribution.

**Example**: Consider the frequency distribution.

 | Class | Frequency | 
 | :-: | :-: |
 | freshman | 12 |
 | sophomore | 10 |
 | junior | 3 |
 | senior | 5 |

***

 | Class | Frequency | 
 | :-: | :-: |
 | freshman | 12 |
 | sophomore | 10 |
 | junior | 3 |
 | senior | 5 |

<br>
If a student is selected at random, the probability of selecting a sophomore is $$\frac{10 \text{ sophomores }}{30 \text{ students}} \approx 0.3333$$ 

***

 | Class | Frequency | 
 | :-: | :-: |
 | freshman | 12 |
 | sophomore | 10 |
 | junior | 3 |
 | senior | 5 |

<br>
The probability of selecting a junior **or** a senior is $$\frac{3\text{ juniors }+5\text{ seniors }}{30\text{ students }} = \frac{8}{30} \approx 0.2667$$

***

 | Class | Frequency | 
 | :-: | :-: |
 | freshman | 12 |
 | sophomore | 10 |
 | junior | 3 |
 | senior | 5 |

<br>
Using probability notation, let $A$ be the event we selected a junior and $B$ be the event we selected a senior. Then $$P(A \text{ or } B) = \frac{8}{30} \approx 0.2667$$