---
title: "3.4 Rules of Probability"
author: "Dr. Lauren Parker"
output: 
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Rules of Probability

Consider a six-sided die. $$P(\text{roll a 1 or 2}) = \frac{\text{2 ways}}{\text{6 outcomes}} = \frac{1}{3}$$ We get the same result by taking $$P(\text{roll a 1})+P(\text{roll a 2}) = \frac{1}{6}+\frac{1}{6} = \frac{1}{3}$$ It turns out this is widely applicable!

## Addition Rule for Disjoint Outcomes

If $A_1$ and $A_2$ are disjoint outcomes, then the probability that one of them occurs is $$P(A_1 \text{ or } A_2) = P(A_1)+P(A_2)$$ This can also be extended to more than two disjoint outcomes: $$P(A_1 \text{ or } A_2 \text{ or } \dots \text{ or } A_k) = P(A_1)+P(A_2)+\dots + P(A_k)$$ for $k$ disjoint outcomes.

## Example: A deck of cards. 

- Let $A$ be the event that a card drawn is a diamond.
- Let $B$ be the event it is a face card. 

$A$: $\quad 2\diamondsuit$ $3\diamondsuit$ $4\diamondsuit$ $5\diamondsuit$ $6\diamondsuit$ $7\diamondsuit$ $8\diamondsuit$ $9\diamondsuit$ $10\diamondsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $A\diamondsuit$

$B$: $\quad J\heartsuit$ $Q\heartsuit$ $K\heartsuit$ $J\clubsuit$ $Q\clubsuit$ $K\clubsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $J\spadesuit$ $Q\spadesuit$ $K\spadesuit$

## Example: A deck of cards.

The collection of cards that are diamonds or face cards (or both) is

<center>$\quad A\diamondsuit$ $2\diamondsuit$ $3\diamondsuit$ $4\diamondsuit$ $5\diamondsuit$ $6\diamondsuit$ $7\diamondsuit$ $8\diamondsuit$ $9\diamondsuit$ $10\diamondsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $J\clubsuit$ $Q\clubsuit$ $K\clubsuit$ $J\heartsuit$ $Q\heartsuit$ $K\heartsuit$ $J\spadesuit$ $Q\spadesuit$ $K\spadesuit$</center>

<br>
Looking at these cards, I can see that there are 22 of them, so $$P(A \text{ or } B) = \frac{22}{52}$$

## Example: A deck of cards.

- If I try to apply the addition rule for disjoint outcomes, $$P(A)=\frac{13}{52}$$ and $$P(B)=\frac{12}{52}$$
- And we get $\frac{13+15}{52} = \frac{25}{52}$.
- But we know $P(A \text{ or } B) = \frac{22}{52}$.

## Example: A deck of cards.

What happened? 

- When I added these, I *double counted* $J\diamondsuit$, $Q\diamondsuit$, and $K\diamondsuit$ 
    - (the cards that are in both $A$ and $B$). 
- I need to subtract off the double count $$\frac{13}{52}+\frac{12}{52}-\frac{3}{52}$$

## General Addition Rule

For any two events $A$ and $B$, the probability that *at least* one will occur is $$P(A \text{ or } B) = P(A)+P(B)-P(A \text{ and }B).$$

- The general addition rule applies to *any* two events, even disjoint events. 
    - For disjoint events, $P(A \text{ and } B) = 0$.

## Inclusive or

- When we say "or", we include the situations where:
    - A is true
    - B is true
    - both A and B are true. 
- This is an *inclusive or*.  

## Complements

The **complement** of an event is all of the outcomes in the sample space that are *not* in the event. For an event $A$, we denote its complement by $A^c$.

## Example

- For a single roll of a six-sided die, the sample space is all possible rolls: 1, 2, 3, 4, 5, or 6. 
- Let event $A$ be rolling a 1 or a 2.
- Then $A^c$ is rolling a 3, 4, 5, or 6. 

In probability notation: $$S = \{1, 2, 3, 4, 5, 6\}$$ $$A=\{1,2\}$$ $$A^c=\{3, 4, 5, 6\}$$

## Property

$$P(A \text{ or } A^c)=1$$ 

- Using the addition rule, $$P(A \text{ or } A^c) = P(A)+P(A^c) = 1$$ 
- Make sure you can convince yourself that $A$ and $A^c$ are *always* disjoint.

## The Complement Rule

$$P(A) = 1-P(A^c)$$

## Checkpoint

Consider rolling 2 six-sided dice and taking their sum. 

The event of interest $A$ is a sum less than 12. Find

1. $A^c$
2. $P(A^c)$
3. $P(A)$

Hint #1: how many ways can you get a sum of at least 12?

Hint #2: there are 36 possible outcomes.