---
title: "Sampling"
output: html_document
---

<p>How do we get samples? We want a sample that represents our population. <strong>Representative samples </strong>reflect the relevant characteristics of our population.&nbsp;</p>
<p>In general, we get representative samples by selecting our samples&nbsp;<em>at random</em> and with an adequate sample size.&nbsp;</p>
<p>A non-representative sample is said to be&nbsp;<strong>biased. </strong>For example, if we used a sample of chihuahuas to represent all dogs, the sample would be biased.&nbsp;</p>
<p>These can be a result of&nbsp;<strong>convenience sampling</strong>, choosing a sample based on ease. In our daily lives, common sources of biases are <strong>anecdotal evidence</strong> and <strong>availability bias</strong>. Anecdotal evidence is data based on personal experience or observation. Typically this consists of only one or two observations and is NOT representative of the population.&nbsp;</p>
<p style="padding-left: 40px;">
    <span style="text-decoration: underline;">Ex: anecdotal evidence</span>. A friend tells you their grandpa smoked a pack of cigarettes a day and lived to be 100. Does this mean that cigarettes will help you live to 100? no!
</p>
<p>Availability bias is your brain's tendency to think that examples of things that come readily to mind are more representative than is actually the case.</p>
<p style="padding-left: 40px;">
    <span style="text-decoration: underline;">Ex. availability bias</span>. Shark attacks. Shark attacks are actually extremely uncommon, but the media tends to report on extreme anecdotes, making us more prone to this kind of bias!
</p>
<p>We avoid bias by taking random samples. One type of random sample is a&nbsp;<strong>simple random sample</strong>. We can think of this as "raffle sampling", like drawing names out of a hat. Each case (or each possible sample) has an equal chance of being selected. Knowing that A is selected doesn't tell us anything about whether B is selected. Instead of drawing from a hat, we usually use a&nbsp;<strong>random number generator</strong> using a computer.</p>

<a href="https://lgpcappiello.github.io/teaching/IntroStats/descriptives/design.html">Next up: Experimental Design</a>

<a href="https://lgpcappiello.github.io/teaching/IntroStats">Return to Course Notes Homepage</a>
